[versions]
kotlin = "1.9.20"
dokka = "1.9.10"

[libraries]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[bundles]

