name: "Build"

on:
  workflow_call:
    inputs:
      build-command:
        required: true
        type: string
    secrets:
      GPG_KEY:
        required: true
      MAVEN_USERNAME:
      MAVEN_PASSWORD:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Import GPG key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_KEY }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew clean ${{ inputs.build-command }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*