name: "Nightly Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github'
      - 'src'
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '.idea/**'
      - .gitignore
      - .gitattributes
      - .editorconfig
      - CODEOWNERS
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - SECURITY.md
      - LICENSE
      - README.md

jobs:
  nightly:
    uses: ./.github/workflows/build.yml
    with:
      build-command: publishMavenJavaPublicationToLocalRepository
    permissions:
      packages: write
      contents: write
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}