name: Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'src'
  push:
    branches:
      - 'master'
    paths:
      - 'src'

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dokka Build
        run: './gradlew dokkaGenerate'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./build/dokkaHtmlOutput
          publish_branch: gh-pages
          destination_dir: ./