name: Publish package to Maven Central

on:
  workflow_dispatch:
jobs:
  staging:
    uses: ./.github/workflows/build.yml
    with:
      build-command: publishToMavenCentral
    permissions:
      packages: write
      contents: write
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MAVEN_USER_TOKEN: ${{ secrets.MAVEN_USER_TOKEN }}